Task 1 [React]
Sir-Alexio/Sir-Alexio.github.io pull request #1
Opened 2024-01-12 15:08 UTC by Sir-Alexio

Первое задание с PropTypes

2024-01-30 17:08 UTC, iDubok requested changes

2024-01-30 17:08 UTC, iDubok commented on src/containers/CounterContainer.js
> +        return <Counter currentCounter={this.state.currentCounter}
Здесь это приемлемо, но в более сложных случаях стоит использовать object destructuring для полей в `state` и `props`.

2024-02-01 15:32 UTC, Sir-Alexio commented on src/views/index.js
> +        <div style={{ marginBottom: '10px' }}>Current count: {props.currentCounter}</div>
Поправил

2024-02-07 14:11 UTC, iDubok approved these changes

2024-02-07 14:11 UTC, iDubok commented on src/views/index.js
> +        <div style={Styles.counterStyle}>Current count: {currentCounter}</div>
Хорошо, только можно не дублировать постфикс `style` на каждом стиле, ведь и так понятно, если это поля класса `Styles`. Другое дело, если стиль динамически считается как переменная, тогда да, стоит называть с постфиксом.

2024-02-12 05:44 UTC, merged