Task1 React TS
Sir-Alexio/Sir-Alexio.github.io pull request #2
Opened 2024-01-13 13:56 UTC by Sir-Alexio

2024-01-30 17:26 UTC, iDubok requested changes

2024-01-30 17:26 UTC, iDubok commented on src/containers/CounterContainer.tsx
> +    state:object;
Для типизации state необходимо использовать отдельный интерфейс и передавать его в `React.Component<PropsType, StateType>`.

2024-02-01 16:10 UTC, Sir-Alexio commented on src/containers/CounterContainer.tsx
> +    state:object;
Поправил

2024-02-08 09:03 UTC, iDubok commented on src/Interfaces/index.ts
> +export interface StateType{
Странно называть interface как "Type". Если в проекте принято называть интерфейсы с префиксом "I", то лучше этого и придерживаться, например, "ICounterState". Но отдельное поле сложного типа в данном случае не нужно, см. комментарий дальше.

2024-02-08 13:57 UTC, iDubok approved these changes

2024-02-08 13:57 UTC, iDubok commented on src/views/index.tsx
> +  const { currentCounter, onIncrementClick, onDecrementClick, onResetClick } =
Можно писать сразу в ```({ currentCounter, onIncrementClick, onDecrementClick, onResetClick }) => {...}```.

2024-02-12 05:50 UTC, merged