Task 3 [React]
Sir-Alexio/Sir-Alexio.github.io pull request #4
Opened 2024-01-17 12:38 UTC by Sir-Alexio

Добавил 3 задание

2024-01-30 20:06 UTC, iDubok requested changes

2024-01-30 20:06 UTC, iDubok commented on src/containers/CounterContainer.tsx
> +      prevCounters = [...counters];
Не стоит изменять параметры методов, если только метод явно не является модификатором входного ссылочного значения. В данном случае, мы должны вернуть новый объект, поэтому стоит объявить его как локальную переменную.
И не очень понятно, зачем входить в зависимость от `counters`, если к тебе в функцию придёт `prevCounters`, с которым нужно работать.

2024-02-04 07:06 UTC, Sir-Alexio commented on src/views/ParentCounter/index.tsx
> +      <div className='counter-block-parent'>
Исправил

2024-02-08 09:19 UTC, iDubok requested changes
Ещё немного)

2024-02-08 09:19 UTC, iDubok commented on src/App.js
> +      <AppBar position="static" style={{ backgroundColor: appBarColor }}>
Для объектов, которые передаём в свойства в компонентах-функциях, стоит использовать `useMemo`.

2024-02-08 09:19 UTC, iDubok commented on src/App.js
> +              color: "white",
`useMemo`

2024-02-08 09:19 UTC, iDubok commented on src/containers/CounterContainer.tsx
> +  }, [counters]);
Аналогично с предыдущим случаем, если можно избавиться от лишней зависимости, это нужно делать.

2024-02-08 09:19 UTC, iDubok commented on src/containers/CounterContainer.tsx
> +  const resetCounters = useCallback(() => {
Можно обойтись без зависимости от `counters`.

2024-02-08 09:19 UTC, iDubok commented on src/containers/CounterContainer.tsx
> +    [counters]
В общем, надеюсь, понятно дальше)

2024-02-08 09:19 UTC, iDubok commented on src/views/Counter/index.tsx
> +const Counter: React.FC<CounterProps> = (props) => {
Можно использовать props destructuring.

2024-02-08 09:19 UTC, iDubok commented on src/views/ParentCounter/index.tsx
> +const ParentCounter: React.FC<ParentCounterProps> = (props) => {
Можно использовать props destructuring.

2024-02-08 14:09 UTC, iDubok requested changes

2024-02-08 14:09 UTC, iDubok commented on src/App.js
> +              color: "white",
Например, запомнить pathname в одном `useMemo`, а потом его использовать в стилях:
```typescript
const tabStyle = useMemo(() => ({
    color: "white",
    backgroundColor: pathname === "/about" ? "#1a1d23" : "transparent",
}), [pathname]);
```

2024-02-08 14:09 UTC, iDubok commented on src/App.js
> +              color: "white",
Да и цвет выделения можно в константы вынести.

2024-02-08 14:09 UTC, iDubok commented on src/views/Counter/index.tsx
>  const Counter: React.FC<CounterProps> = (props) => {
```suggestion
const Counter: React.FC<CounterProps> = ({ index, currentCounter, onIncrement, onDecrement, onReset }) => {
```

2024-02-08 14:09 UTC, iDubok commented on src/views/Counter/index.tsx
> +  const { index, currentCounter, onIncrement, onDecrement, onReset } = props;
```suggestion
```

2024-02-08 14:09 UTC, iDubok commented on src/views/ParentCounter/index.tsx
> +const ParentCounter: React.FC<ParentCounterProps> = (props) => {
См. пример выше.

2024-02-09 13:43 UTC, iDubok commented on src/App.js
> +  const appBarColor = "#0f1116";
Если можно вынести константу наружу компонента, это нужно делать.

2024-02-12 05:59 UTC, merged