Task 4 [React]
Sir-Alexio/Sir-Alexio.github.io pull request #5
Opened 2024-01-17 18:21 UTC by Sir-Alexio

Добавил 4 задание

2024-01-30 20:34 UTC, iDubok requested changes

2024-01-30 20:34 UTC, iDubok commented on src/views/Login/index.tsx
> +  onButtonClick: () => void;
Логичнее было бы назвать `onFormSubmit`.

2024-01-30 20:34 UTC, iDubok commented on src/containers/LoginContainer.tsx
> +    if (event.key === "Enter") {
По сути, логику отправки формы по нажатию на Enter в поле можно было бы инкапсулировать в компонент формы, при этом при необходимости выбросив свойство-флажок, выключающий такое поведение.

2024-01-30 20:34 UTC, iDubok commented on src/containers/LoginContainer.tsx
> +interface IData {
Не стоит дублировать интерфейсы в каждом файле. Можно вынести их в файл в папке types и импортировать оттуда.

2024-01-30 20:34 UTC, iDubok commented on src/containers/LoginContainer.tsx
> +    const onEmailChange = (event: React.ChangeEvent<HTMLInputElement>)=>{
Используй `useCallback` здесь и далее.

2024-01-30 20:39 UTC, iDubok requested changes

2024-01-30 20:39 UTC, iDubok commented on src/containers/CounterContainer.tsx
> +import ParentCounter from '../views/ParentCounter/index';
Потренируйся добавить path в tsconfig, чтобы мочь писать `@/views/ParentCounter` вместо этого.

2024-02-04 07:38 UTC, Sir-Alexio commented on src/containers/LoginContainer.tsx
> +    if (event.key === "Enter") {
Здесь не очень понял. Я могу добавить флажок:
![image](https://github.com/Sir-Alexio/Sir-Alexio.github.io/assets/73094043/c0c6980b-271b-49d6-9c05-184b37d0a90c)
Как этот флажок использовать потом в компоненте формы логина? И нужно перенести всю логику нажатия на enter непосредственно в форму Login?

2024-02-04 11:37 UTC, Sir-Alexio commented on src/containers/CounterContainer.tsx
> +import ParentCounter from '../views/ParentCounter/index';
Как я понял, можно определить baseUrl в ts.config и пути будут выглядеть так: 
![image](https://github.com/Sir-Alexio/Sir-Alexio.github.io/assets/73094043/7d051f24-dc12-4661-9a17-b896bb2d2b29)
Зачем тогда нужны псевдонимы?

2024-02-08 13:53 UTC, iDubok requested changes

2024-02-08 13:53 UTC, iDubok commented on src/containers/CounterContainer.tsx
>    const addNewCounter = () => {
Здесь и далее не хватает `useCallback` + замечания из предыдущего задания.

2024-02-09 13:51 UTC, iDubok approved these changes

2024-02-09 13:58 UTC, iDubok requested changes

2024-02-09 13:58 UTC, iDubok commented on src/containers/CounterContainer.tsx
> +    if (counters.length > 1) {
Так а почему бы не внести эту проверку в метод в `setCounters`, чтобы и здесь избавиться от зависимостей?

Если вернуть то же состояние в `setState`, ре-рендера не должно быть.

2024-02-11 17:18 UTC, iDubok approved these changes

2024-02-12 06:02 UTC, merged