Task6 [Formik]
Sir-Alexio/Sir-Alexio.github.io pull request #7
Opened 2024-01-22 12:56 UTC by Sir-Alexio

Добавил 6 задание

2024-01-31 09:36 UTC, iDubok requested changes

2024-01-31 09:36 UTC, iDubok commented on src/views/FormikSuccess/index.tsx
> +                style: { color: 'white', borderBottom: '1px solid white', marginBottom: '25.92px', width: '259.2px' },
В реальном проекте так верстать не надо)
Стили в стили, также по возможности нужно использовать относительные единицы измерения и респонсивную вёрстку.

2024-01-31 09:36 UTC, iDubok commented on src/views/LoginFormik/index.tsx
> +      initialValues={{ email: '', password: '' }}
Значения по умолчанию должны быть вынесены в константу. Следует избегать объектов и функций прямо в свойствах компонентов, т. к. это приводит к лишним перерисовкам.

2024-01-31 09:36 UTC, iDubok commented on src/views/LoginFormik/index.tsx
> +        onEmailChange(fakeEvent);
Более универсальный сервис/хук должен принимать более общий вид события, т. е. просто новое значение определённого поля, чтобы не зависеть от него и не городить фейки.

2024-01-31 09:36 UTC, iDubok commented on src/views/LoginFormik/index.tsx
> +      onSubmit={(values: IFormValues, { setSubmitting }: FormikHelpers<IFormValues>) => {
Все свойства, передаваемые в компонент, должны быть либо свойствами извне, либо константами, либо локальным состоянием, либо закэшированными с помощью `useCallback` и `useMemo` значениями.

2024-01-31 09:36 UTC, iDubok commented on src/views/LoginFormik/index.tsx
> +      onSubmit={(values: IFormValues, { setSubmitting }: FormikHelpers<IFormValues>) => {
Конечно, если это возможно в конкретной ситуации.

2024-01-31 09:39 UTC, iDubok commented
Попробуй использовать yup для валидации формы в связке с formik, станет гораздо лаконичнее:
https://formik.org/docs/tutorial#schema-validation-with-yup

2024-02-05 14:13 UTC, Sir-Alexio commented on src/views/FormikSuccess/index.tsx
> +                style: { color: 'white', borderBottom: '1px solid white', marginBottom: '25.92px', width: '259.2px' },
Вся проблема в том, что у компонентов библиотеки materialUI определены свои стили и чтобы как то изменить их  вид нужно определять стиль прямо в месте использования компонента. Вероятно есть какой то секрет, как надо делать правильно, но пока я его не нашел)

2024-02-06 05:03 UTC, Sir-Alexio commented on src/views/FormikSuccess/index.tsx
> +                style: { color: 'white', borderBottom: '1px solid white', marginBottom: '25.92px', width: '259.2px' },
Почти полностью исправил

2024-02-08 15:50 UTC, iDubok requested changes
Комменты предыдущих заданий + эти новые.

2024-02-08 15:50 UTC, iDubok commented on src/views/LoginFormik/index.tsx
> +  const validationSchema = Yup.object().shape({
Схемы валидации лучше выносить в отдельный файл, или хотя бы вне компонента.

2024-02-08 15:50 UTC, iDubok commented on src/views/LoginFormik/index.tsx
> +  const initialState = { email: "", password: "" };
Если можно вынести в константу вне компонента — это нужно делать. Лишнее пересоздание объектов при ре-рендере нам ни к чему.

2024-02-08 15:50 UTC, iDubok commented on src/views/LoginFormik/index.tsx
> +        onSubmit={(values: IFormValues) => {
Тела функций не должны сидеть в свойствах компонентов. `useCallback`!

2024-02-08 15:50 UTC, iDubok commented on src/views/LoginFormik/index.tsx
> +        onSubmit={(values: IFormValues) => {
Думаю, ты уже знаешь об этом, просто нужно стараться выносить везде, а не только, где я не пропустил.

2024-02-09 14:42 UTC, iDubok approved these changes

2024-02-09 14:42 UTC, iDubok commented on src/views/LoginFormik/index.tsx
> +  }, []);
В данном случае `onEmailChange` и `onPasswordChange` тоже следует помесить в зависмости.

2024-02-12 06:10 UTC, merged